### ISSUE TITLE
Unable to build with `openssl 0.10.39`: cannot find function, tuple struct or tuple variant in crate `ffi`

### ISSUE THREAD

**Issue by pan93412** [sfackler/rust-openssl#1630]
Seems like there are some breaking changes introduced in the `openssl-sys v0.9.73` version.

```
error[E0425]: cannot find function, tuple struct or tuple variant `BIO_meth_set_write__fixed_rust` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/bio.rs:208:30
    |
208 |                     cvt(ffi::BIO_meth_set_write__fixed_rust(method.0, Some(bwrite::<S>)))?;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `BIO_meth_set_read__fixed_rust` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/bio.rs:209:30
    |
209 |                     cvt(ffi::BIO_meth_set_read__fixed_rust(method.0, Some(bread::<S>)))?;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `BIO_meth_set_puts__fixed_rust` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/bio.rs:210:30
    |
210 |                     cvt(ffi::BIO_meth_set_puts__fixed_rust(method.0, Some(bputs::<S>)))?;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `BIO_meth_set_ctrl__fixed_rust` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/bio.rs:211:30
    |
211 |                     cvt(ffi::BIO_meth_set_ctrl__fixed_rust(method.0, Some(ctrl::<S>)))?;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `BIO_meth_set_create__fixed_rust` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/bio.rs:212:30
    |
212 |                     cvt(ffi::BIO_meth_set_create__fixed_rust(method.0, Some(create)))?;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `BIO_meth_set_destroy__fixed_rust` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/bio.rs:213:30
    |
213 |                     cvt(ffi::BIO_meth_set_destroy__fixed_rust(method.0, Some(destroy::<S>)))?;
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `SSL_CTX_set_tlsext_servername_callback__fixed_rust` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/mod.rs:726:18
    |
726 |               ffi::SSL_CTX_set_tlsext_servername_callback__fixed_rust(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `SSL_CTX_set_tlsext_servername_callback`
    |
   ::: /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.72/src/tls1.rs:85:1
    |
85  | / pub unsafe fn SSL_CTX_set_tlsext_servername_callback(
86  | |     ctx: *mut SSL_CTX,
87  | |     // FIXME should have the right signature
88  | |     cb: Option<extern "C" fn()>,
89  | | ) -> c_long {
    | |___________- similarly named function `SSL_CTX_set_tlsext_servername_callback` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `SSL_CTX_set_tmp_dh_callback__fixed_rust` in crate `ffi`
    --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/mod.rs:808:18
     |
808  |               ffi::SSL_CTX_set_tmp_dh_callback__fixed_rust(self.as_ptr(), Some(raw_tmp_dh::<F>));
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `SSL_CTX_set_tmp_dh_callback`
     |
    ::: /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.72/src/ssl.rs:1334:5
     |
1334 | /     pub fn SSL_CTX_set_tmp_dh_callback(
1335 | |         ctx: *mut SSL_CTX,
1336 | |         dh: unsafe extern "C" fn(ssl: *mut SSL, is_export: c_int, keylength: c_int) -> *mut DH,
1337 | |     );
     | |______- similarly named function `SSL_CTX_set_tmp_dh_callback` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `SSL_CTX_set_alpn_select_cb__fixed_rust` in crate `ffi`
    --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/mod.rs:1207:18
     |
1207 |               ffi::SSL_CTX_set_alpn_select_cb__fixed_rust(
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `SSL_CTX_set_alpn_select_cb`
     |
    ::: /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.72/src/ssl.rs:639:5
     |
639  | /     pub fn SSL_CTX_set_alpn_select_cb(
640  | |         ssl: *mut SSL_CTX,
641  | |         cb: extern "C" fn(
642  | |             ssl: *mut SSL,
...    |
649  | |         arg: *mut c_void,
650  | |     );
     | |______- similarly named function `SSL_CTX_set_alpn_select_cb` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `SSL_set_tmp_dh_callback__fixed_rust` in crate `ffi`
    --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/ssl/mod.rs:2288:18
     |
2288 |             ffi::SSL_set_tmp_dh_callback__fixed_rust(self.as_ptr(), Some(raw_tmp_dh_ssl::<F>));
     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

error[E0425]: cannot find function, tuple struct or tuple variant `X509_issuer_name_hash` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/x509/mod.rs:399:23
    |
399 |         unsafe { ffi::X509_issuer_name_hash(self.as_ptr()) as u32 }
    |                       ^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `X509_subject_name_hash`
    |
   ::: /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.72/src/x509.rs:336:5
    |
336 |     pub fn X509_subject_name_hash(x: *mut ::X509) -> c_ulong;
    |     --------------------------------------------------------- similarly named function `X509_subject_name_hash` defined here

error[E0425]: cannot find function, tuple struct or tuple variant `X509_print` in crate `ffi`
   --> /Users/pan93412/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.39/src/x509/mod.rs:588:14
    |
588 |         ffi::X509_print
    |              ^^^^^^^^^^ not found in `ffi`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `openssl` due to 12 previous errors
```

**Comment by sfackler** [comment]
Oops, I forgot to update openssl's version requirement on openssl-sys. A `cargo update` should git it compiling.

**Comment by bgilbert** [comment]
Would you consider releasing a new version with this fix, so everyone doesn't need to manually fix up their Dependabot PRs?

**Comment by sfackler** [comment]
Yep, done
