### ISSUE TITLE
Does not compile on fresh Ubuntu 16.04

### ISSUE THREAD

**Issue by cars10** [sfackler/rust-openssl#463]
Cargo Version: cargo 0.8.0 (built 2016-03-22)
Rustc Version: rustc 1.7.0

Error:

 ```
Compiling openssl-sys v0.7.17
failed to run custom build command for `openssl-sys-extras v0.7.14`
Process didn't exit successfully: `/home/cars10/rse/target/debug/build/openssl-sys-extras-293d514e4658787c/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-unknown-linux-gnu")
debug=true opt-level=0
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/home/cars10/rse/target/debug/build/openssl-sys-extras-293d514e4658787c/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
cargo:warning=src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
cargo:warning=compilation terminated.
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread '<main>' panicked at 'explicit panic', /home/cars10/.cargo/registry/src/github.com-88ac128001ac3a9a/gcc-0.3.35/src/lib.rs:897
```

Edit: same error with nightly of rustc+cargo

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-openssl#linux

cargo clean after installing.
