### ISSUE TITLE
Breaking change to openssl-sys with semver compatible version number?

### ISSUE THREAD

**Issue by jonathanpallant** [sfackler/rust-openssl#1632]
Hi!

I use openssl pinned at `=0.10.29` in a production application. Today my program failed to build.

It appears that the resolver has picked up `openssl-sys 0.9.73`. This is the latest semver compatible version for the `0.9.55` [specified in the Cargo.toml](https://github.com/sfackler/rust-openssl/blob/openssl-v0.10.29/openssl/Cargo.toml#L28).

Unfortunately `openssl-sys 0.9.73` does not work with `openssl 0.10.29`.

```
$ cargo build my-secret-app
...
error[E0308]: mismatched types
    --> /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.29/src/ssl/mod.rs:1666:22
     |
1666 |                 Some(raw_custom_ext_free::<T>),
     |                      ^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
     |
     = note: expected fn pointer `unsafe extern "C" fn(_, _, _, *const u8, _)`
                   found fn item `extern "C" fn(_, _, _, *mut *const u8, _) {callbacks::raw_custom_ext_free::<T>}`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `openssl`.
```

The diff shows:

```console
$ git diff openssl-sys-v0.9.72 openssl-sys-v0.9.73 -- openssl/src/ssl/callbacks.rs | cat
diff --git a/openssl/src/ssl/callbacks.rs b/openssl/src/ssl/callbacks.rs
index 116c5445..f33f6ec0 100644
--- a/openssl/src/ssl/callbacks.rs
+++ b/openssl/src/ssl/callbacks.rs
@@ -612,7 +612,7 @@ pub extern "C" fn raw_custom_ext_free<T>(
     ssl: *mut ffi::SSL,
     _: c_uint,
     _: c_uint,
-    _: *mut *const c_uchar,
+    _: *const c_uchar,
     _: *mut c_void,
 ) where
     T: 'static + Sync + Send,
```

Adding `openssl-sys = "=0.9.72"` as a dependency to my application to force the selection of the older version fixes the issue and my application builds again.

**Comment by jonathanpallant** [comment]
I totally accept the breaking change was necessary for correctness. I'm just unclear why it didn't result in a change to the major version number to indicate that this had happened.

**Comment by sfackler** [comment]
Major version number bumps of -sys crates are profoundly impactful to the ecosystem, because Cargo is unwilling to link 2 of them at the same time.

**Comment by sfackler** [comment]
openssl v0.10.39 was released alongside openssl-sys 0.9.73.

**Comment by jonathanpallant** [comment]
https://packages.debian.org/bullseye/librust-openssl-dev shows 0.10.29
https://packages.debian.org/bullseye/librust-openssl-sys-dev shows 0.9.55

But, honestly, we can close this issue. I highlighted a semver-compatible breaking change, and if the project response is "yeah, tough - security trumps that" then I will find a way to live with that.

**Comment by asgrim** [comment]
OK, if I understand correctly, the correct solution is to update `Cargo.toml` to be:

```toml
[dependencies]
openssl-sys = { version = ">0.9.73", features = ["vendored"] }
openssl = ">0.10.39"
```

Thank you

**Comment by sfackler** [comment]
The openssl crate already declares that dependency constraint on openssl-sys - you don't need to separately specify openssl-sys there.
