### ISSUE TITLE
Cannot Build with OpenSSL 1.1.1f on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by shrimpwtf** [sfackler/rust-openssl#2306]
`usr/bin/ld: /root/testing/target/debug/deps/libreqwest-e63f940b995b3a5a.rlib(reqwest-e63f940b995b3a5a.reqwest.2b69ba60e2e131ae-cgu.03.rcgu.o): in function `openssl::ssl::SslStream<S>::ssl_read_uninit':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-0.10.66/src/ssl/mod.rs:3786: undefined reference to `SSL_read_ex'
    /usr/bin/ld: /root/testing/target/debug/deps/libreqwest-e63f940b995b3a5a.rlib(reqwest-e63f940b995b3a5a.reqwest.2b69ba60e2e131ae-cgu.03.rcgu.o): in function `openssl::ssl::SslStream<S>::ssl_read_uninit':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-0.10.66/src/ssl/mod.rs:3786: undefined reference to `SSL_read_ex'
    /usr/bin/ld: /root/testing/target/debug/deps/libreqwest-e63f940b995b3a5a.rlib(reqwest-e63f940b995b3a5a.reqwest.2b69ba60e2e131ae-cgu.03.rcgu.o): in function `openssl::ssl::SslStream<S>::ssl_write':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-0.10.66/src/ssl/mod.rs:3827: undefined reference to `SSL_write_ex'
    /usr/bin/ld: /root/testing/target/debug/deps/libreqwest-e63f940b995b3a5a.rlib(reqwest-e63f940b995b3a5a.reqwest.2b69ba60e2e131ae-cgu.03.rcgu.o): in function `openssl::ssl::SslStream<S>::ssl_write':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-0.10.66/src/ssl/mod.rs:3827: undefined reference to `SSL_write_ex'
    /usr/bin/ld: /root/testing/target/debug/deps/libopenssl_sys-4170f4211535d644.rlib(openssl_sys-4170f4211535d644.openssl_sys.74c5284e5add6480-cgu.0.rcgu.o): in function `openssl_sys::openssl::ssl::SSL_CTX_set_mode':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.103/src/./ssl.rs:246: undefined reference to `SSL_CTX_ctrl'
    /usr/bin/ld: /root/testing/target/debug/deps/libopenssl_sys-4170f4211535d644.rlib(openssl_sys-4170f4211535d644.openssl_sys.74c5284e5add6480-cgu.0.rcgu.o): in function `openssl_sys::openssl::ssl::SSL_CTX_add_extra_chain_cert':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.103/src/./ssl.rs:384: undefined reference to `SSL_CTX_ctrl'
    /usr/bin/ld: /root/testing/target/debug/deps/libopenssl_sys-4170f4211535d644.rlib(openssl_sys-4170f4211535d644.openssl_sys.74c5284e5add6480-cgu.0.rcgu.o): in function `openssl_sys::openssl::tls1::SSL_set_tlsext_host_name':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.103/src/./tls1.rs:24: undefined reference to `SSL_ctrl'
    /usr/bin/ld: /root/testing/target/debug/deps/libopenssl_sys-4170f4211535d644.rlib(openssl_sys-4170f4211535d644.openssl_sys.74c5284e5add6480-cgu.0.rcgu.o): in function `openssl_sys::openssl::ssl::SSL_CTX_set_min_proto_version':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.103/src/./ssl.rs:459: undefined reference to `SSL_CTX_ctrl'
    /usr/bin/ld: /root/testing/target/debug/deps/libopenssl_sys-4170f4211535d644.rlib(openssl_sys-4170f4211535d644.openssl_sys.74c5284e5add6480-cgu.0.rcgu.o): in function `openssl_sys::openssl::ssl::SSL_CTX_set_max_proto_version':
    /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.103/src/./ssl.rs:468: undefined reference to `SSL_CTX_ctrl'
    collect2: error: ld returned 1 exit status`
    
    
    `apt search ^libssl | grep installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libssl-dev/focal-updates,focal-security,now 1.1.1f-1ubuntu2.23 amd64 [installed]
libssl1.1/focal-updates,focal-security,now 1.1.1f-1ubuntu2.23 amd64 [installed]`

**Comment by maxiloEmmmm** [comment]
same
