### ISSUE TITLE
Failed to build on OS X

### ISSUE THREAD

**Issue by zonyitoo** [sfackler/rust-openssl#650]
1. OS X 10.12.5 (16F73)
2. rustc 1.18.0 (03fc9d622 2017-06-06)
3. openssl v0.9.13 (from crates.io)
4. OpenSSL 1.0.2l (from HomeBrew)

Error logs:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/ssserver-0f19d6c10214d296.0.o" "-o" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/ssserver-0f19d6c10214d296" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps" "-L" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/build/ring-5d28e63d6fe2f47c/out" "-L" "/usr/local/Cellar/libsodium/1.0.12/lib" "-L" "/usr/local/opt/openssl@1.1/lib" "-L" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libclap-6938e7a78fa70c1e.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libterm_size-3e8f48b7d12b3f0f.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libvec_map-6792fa78676b5ba7.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libbitflags-40c9799a6d297c75.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libshadowsocks-ad71759b73bed7d8.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libring-48631566cedde8fe.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libmd_5-3bcae197510e72f1.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libdigest_buffer-e1826999685b1516.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/liblru_cache-0d555aabc17b7664.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/liblinked_hash_map-de1a7f979c099c7e.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libserde_json-792616b63a660205.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libnum_traits-32c57ec3799391e2.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libdigest-2fabb90b6316440c.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libgeneric_array-cb6ad2612af11088.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libtypenum-54c183458bba9a50.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libenv_logger-337736c567827560.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libregex-f57600d45f59abf1.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libutf8_ranges-b81dc320c0a952bb.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libregex_syntax-0240ebb185fe3635.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libaho_corasick-ee2f3809623d70dc.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libmemchr-69681615927cea24.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libunicode_width-a9324100be4d7255.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libatty-6b30b4e55215ba1b.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libdtoa-5b7f1650e7fc4bdd.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libbyte_tools-fdbbe2dbc011a24f.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libnum_cpus-1744e8bc49f70b5a.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libansi_term-2c381dad284859c7.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libunicode_segmentation-64ceb3575fa375ed.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libitoa-a2260b7adc104971.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libopenssl-e2738a4bca71d132.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libopenssl_sys-344d1d57c032c9b7.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/liblazy_static-18005fa1be5dd889.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libforeign_types-4224a6bfe004c283.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libbitflags-c8b3e4b415593713.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libdomain-aeffb38889760c18.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libtokio_core-a08697205148329f.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libtokio_io-b05415e36730f2f0.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libbytes-bbb7bd4f6364cc42.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libbyteorder-190c8b8b4cb7f472.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/librand-76456d761c2cb637.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libfutures-3c38b04c521398ed.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libbyteorder-fadd50430087d61b.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libthread_local-273e90e65080c55f.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libunreachable-9bd306f72d3bd51e.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libvoid-6c52c4ddaea6e3db.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libthread_id-9aba8731d7b3c119.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libtime-162277ce7a864579.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libstrsim-5216133a64737ad9.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/liblru_time_cache-11b283842bb68121.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libnodrop-e6d7a15cb157c190.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libodds-4d86427aaea60869.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libuntrusted-a324c79fdd62d8cc.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libsodiumoxide-5a96141669fe57ed.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libserde-78efb8229e554e58.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/liblibsodium_sys-b88c2080a51f2b89.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libmio-24ed8f4e89aa6126.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/liblog-4cfe391024f1467d.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libiovec-6456cca526bac37d.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libslab-18a7cdae03894a24.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libnet2-be2dd9956e589540.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libcfg_if-d561b8f41e038432.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/liblibc-496b028781a2b35b.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/liblazycell-43df05f1cf6910d1.rlib" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/deps/libscoped_tls-74736eecfdde68b3.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-d19edcdb8b3582f0.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-35809200ab841b7b.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-dd5cb334048ac204.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librand-eb0e42c8ae609eea.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcollections-6fcbe3ecfbfa6629.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-7f2c52501770c1c7.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_jemalloc-ea49ffd3fee5264c.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-4ac31620c28c3400.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd_unicode-7e35037032e227eb.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-10c94a1f2bd23f41.rlib" "/Users/zonyitoo/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-1afcf087346e8edb.rlib" "-framework" "Security" "-l" "ssl" "-l" "crypto" "-l" "sodium" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m"
  = note: Undefined symbols for architecture x86_64:
            "_SSL_library_init", referenced from:
                openssl_sys::ossl10x::init::_$u7b$$u7b$closure$u7d$$u7d$::h2f775cbe764542ab in libopenssl_sys-344d1d57c032c9b7.rlib(openssl_sys-344d1d57c032c9b7.0.o)
            "_OPENSSL_add_all_algorithms_noconf", referenced from:
                openssl_sys::ossl10x::init::_$u7b$$u7b$closure$u7d$$u7d$::h2f775cbe764542ab in libopenssl_sys-344d1d57c032c9b7.rlib(openssl_sys-344d1d57c032c9b7.0.o)
            "_SSL_load_error_strings", referenced from:
                openssl_sys::ossl10x::init::_$u7b$$u7b$closure$u7d$$u7d$::h2f775cbe764542ab in libopenssl_sys-344d1d57c032c9b7.rlib(openssl_sys-344d1d57c032c9b7.0.o)
            "_CRYPTO_num_locks", referenced from:
                openssl_sys::ossl10x::init::_$u7b$$u7b$closure$u7d$$u7d$::h2f775cbe764542ab in libopenssl_sys-344d1d57c032c9b7.rlib(openssl_sys-344d1d57c032c9b7.0.o)
            "_CRYPTO_set_id_callback", referenced from:
                openssl_sys::ossl10x::set_id_callback::h5cd8df21446972c4 in libopenssl_sys-344d1d57c032c9b7.rlib(openssl_sys-344d1d57c032c9b7.0.o)
            "_CRYPTO_set_locking_callback", referenced from:
                openssl_sys::ossl10x::init::_$u7b$$u7b$closure$u7d$$u7d$::h2f775cbe764542ab in libopenssl_sys-344d1d57c032c9b7.rlib(openssl_sys-344d1d57c032c9b7.0.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It is Ok to build this crate separately, but links failed in [my project](https://github.com/zonyitoo/shadowsocks-rust). Can't find a clue, please help.

NOTE: It was Ok to build with rustc 1.17.

**Comment by sfackler** [comment]
It looks like it's finding headers for OpenSSL 1.0.2, but linking to OpenSSL 1.1.0, which is weird: `"-L" "/usr/local/opt/openssl@1.1/lib"`

Could you grab the contents of the `target/debug/build/openssl-sys-41a2c1e2a1966dbc/output`?

**Comment by zonyitoo** [comment]
I can't find any directories like `target/debug/build/openssl-sys-41a2c1e2a1966dbc/output`, but I found followings:

```
$ find . -name "openssl*"
./src/crypto/openssl.rs
./target/debug/.fingerprint/openssl-601af1e10ce24902
./target/debug/.fingerprint/openssl-e2738a4bca71d132
./target/debug/.fingerprint/openssl-ec6805437df836e8
./target/debug/.fingerprint/openssl-sys-2d63b37cbe94e650
./target/debug/.fingerprint/openssl-sys-344d1d57c032c9b7
./target/debug/.fingerprint/openssl-sys-c8f65163ef99ca06
./target/debug/build/openssl-601af1e10ce24902
./target/debug/build/openssl-ec6805437df836e8
./target/debug/build/openssl-sys-2d63b37cbe94e650
./target/debug/build/openssl-sys-c8f65163ef99ca06
```

And the content of `./target/debug/build/openssl-sys-2d63b37cbe94e650/output` is

```
cargo:rustc-link-search=native=/usr/local/opt/openssl@1.1/lib
cargo:include=/usr/local/opt/openssl/include
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "/usr/local/opt/openssl/include" "-E" "/Users/zonyitoo/Projects/shadowsocks-rust/target/debug/build/openssl-sys-2d63b37cbe94e650/out/expando.c"
exit code: 0
cargo:rustc-cfg=osslconf="OPENSSL_NO_KRB5"
cargo:rustc-cfg=osslconf="OPENSSL_NO_RFC3779"
cargo:conf=OPENSSL_NO_KRB5,OPENSSL_NO_RFC3779
cargo:rustc-cfg=ossl102
cargo:version=102
cargo:rustc-link-lib=dylib=ssl
cargo:rustc-link-lib=dylib=crypto
```

and the content of directory `./target/debug/build/openssl-sys-c8f65163ef99ca06` is

```
ls ./target/debug/build/openssl-sys-c8f65163ef99ca06
build-script-build                       build_script_build-c8f65163ef99ca06.dSYM
build_script_build-c8f65163ef99ca06
```

**Comment by zonyitoo** [comment]
So the problem should be:

```
cargo:rustc-link-search=native=/usr/local/opt/openssl@1.1/lib
cargo:include=/usr/local/opt/openssl/include
```

**Comment by sfackler** [comment]
Oh, I bet you have `OPENSSL_INCLUDE_DIR` set to `/usr/local/opt/openssl/include` but not `OPENSSL_LIB_DIR`. The build script then discovers the OpenSSL 1.1 directory and uses that for the libraries. If you unset that variable you should be good to go.

**Comment by zonyitoo** [comment]
Ah.. Yes, you are right! Thanks!!
