### ISSUE TITLE
SSLv23_method to be removed in future OpenSSL

### ISSUE THREAD

**Issue by jethrogb** [sfackler/rust-openssl#220]
Heads up: https://github.com/openssl/openssl/commit/32ec41539b5b23bc42503589fcc5be65d648d1f5

For all practical purposes, `TLS_method` is a drop-in replacement for `SSLv23_method`.

**Comment by sfackler** [comment]
Thanks for the heads up. Looks like it should be straightforward to shim around in a reasonable way.

**Comment by mbrubeck** [comment]
The latest version of openssl in Debian testing/unstable is built with no-ssl3-method, so rust-openssl fails to link with `error: undefined reference to 'SSLv3_method`.

**Comment by sfackler** [comment]
Yeah, I have a pending breaking changes release that will make SSLv3 opt-in. I'll roll it out tonight.

**Comment by ShaunGillies** [comment]
Was that ever released?

**Comment by Thooms** [comment]
@sfackler would you mind giving an update here? Do you need someone to take care of it :)?

**Comment by sfackler** [comment]
I don't think there's any action to take yet, as I don't believe the openssl commit's hit a release.

**Comment by sfackler** [comment]
I'm working on 1.1 support on the breaks branch. The changes in OpenSSL will probably force a breaking release for this library as well.

**Comment by alexcrichton** [comment]
This should be handled in https://github.com/sfackler/rust-openssl/pull/464
