### ISSUE TITLE
systest compilation fails on Debian stretch

### ISSUE THREAD

**Issue by mbr** [sfackler/rust-openssl#911]
On a stock Debian 9 with OpenSSL installed, I get the following error during building:

```
error: failed to run custom build command for `systest v0.1.0 (file:///home/marc/Documents/github.com/sfackler/rust-openssl/systest)`
process didn't exit successfully: `/home/marc/Documents/github.com/sfackler/rust-openssl/target/debug/build/systest-61685f7c7862e71a/build-script-build` (exit code: 101)
--- stdout
-----------------------------------------
cargo:rerun-if-changed=../openssl-sys/src/lib.rs
cargo:rerun-if-changed=../openssl-sys/src/ossl110.rs
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-o" "/home/marc/Documents/github.com/sfackler/rust-openssl/target/debug/build/systest-f2dc17a2b45ef384/out/all.o" "-c" "/home/marc/Documents/github.com/sfackler/rust-openssl/target/debug/build/systest-f2dc17a2b45ef384/out/all.c"
cargo:warning=/home/marc/Documents/github.com/sfackler/rust-openssl/target/debug/build/systest-f2dc17a2b45ef384/out/all.c:34:74: error: ‘SSL_CTRL_GET_MIN_PROTO_VERSION’ undeclared here (not in a function)
cargo:warning=             static int __test_const_SSL_CTRL_GET_MIN_PROTO_VERSION_val = SSL_CTRL_GET_MIN_PROTO_VERSION;
cargo:warning=                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/home/marc/Documents/github.com/sfackler/rust-openssl/target/debug/build/systest-f2dc17a2b45ef384/out/all.c:40:74: error: ‘SSL_CTRL_GET_MAX_PROTO_VERSION’ undeclared here (not in a function)
cargo:warning=             static int __test_const_SSL_CTRL_GET_MAX_PROTO_VERSION_val = SSL_CTRL_GET_MAX_PROTO_VERSION;
cargo:warning=                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-o" "/home/marc/Documents/github.com/sfackler/rust-openssl/target/debug/build/systest-f2dc17a2b45ef384/out/all.o" "-c" "/home/marc/Documents/github.com/sfackler/rust-openssl/target/debug/build/systest-f2dc17a2b45ef384/out/all.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/marc/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.15/src/lib.rs:2158:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

This might not be big of a deal (removing `systest` from the workspace members is a workaround), but I git-bisected to b7ba5773, which seems to be the culprit.

**Comment by sfackler** [comment]
Ah, looks like those weren't added until 1.1.0g. Should be fixable like we handled #908
