### PR TITLE
Support libressl 2.8.0

### LINKED ISSUE #988: Does not build with LibreSSL 2.8.0
Hi,

LibreSSL 2.8.0 is released but not supported by this crate. Bumping the version numbers in the build scripts is not enough to compile it: There have been some `const` changes in LibreSSL that break tests and most likely the build as well.

This also repeats #939 and breaks the crate and any dependents on OpenBSD 6.4-beta which comes with LibreSSL 2.8.0.

Is there any work on supporting LibreSSL 2.8.0 yet or should we look into it?

Reyk

```make
   Compiling systest v0.1.0 (file:///rust/rust-openssl/systest)
error: failed to run custom build command for `systest v0.1.0 (file:///rust/rust-openssl/systest)`
process didn't exit successfully: `/rust/rust-openssl/target/debug/build/systest-d7f8964f8ffe8d09/build-script-build` (exit code: 101)
--- stdout
-----------------------------------------
cargo:rerun-if-changed=../openssl-sys/src/lib.rs
cargo:rerun-if-changed=../openssl-sys/src/libressl/mod.rs
cargo:rerun-if-changed=../openssl-sys/src/libressl/v251.rs
cargo:rerun-if-changed=../openssl-sys/src/libressl/v273.rs
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-openbsd")
HOST = Some("x86_64-unknown-openbsd")
CC_x86_64-unknown-openbsd = None
CC_x86_64_unknown_openbsd = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-openbsd")
HOST = Some("x86_64-unknown-openbsd")
CFLAGS_x86_64-unknown-openbsd = None
CFLAGS_x86_64_unknown_openbsd = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
HOST = Some("x86_64-unknown-openbsd")
CFLAGS_x86_64-unknown-openbsd = None
CFLAGS_x86_64_unknown_openbsd = None
HOST_CFLAGS = None
CFLAGS = None
HOST = Some("x86_64-unknown-openbsd")
CFLAGS_x86_64-unknown-openbsd = None
CFLAGS_x86_64_unknown_openbsd = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-o" "/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.o" "-c" "/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c"
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:1461:28: error: returning 'const BIO_METHOD **' (aka 'const struct bio_method_st **') from a function with result type 'BIO_METHOD **' (aka 'struct bio_method_st **') discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
cargo:warning=                    return &b->method;
cargo:warning=                           ^~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2776:24: error: incompatible pointer types returning 'BIO *(const BIO_METHOD *)' (aka 'struct bio_st *(const struct bio_method_st *)') from a function with result type 'BIO *(*)(BIO_METHOD *)' (aka 'struct bio_st *(*)(struct bio_method_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return BIO_new;
cargo:warning=                       ^~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2781:24: error: incompatible pointer types returning 'const BIO_METHOD *(void)' (aka 'const struct bio_method_st *(void)') from a function with result type 'BIO_METHOD *(*)(void)' (aka 'struct bio_method_st *(*)(void)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return BIO_s_file;
cargo:warning=                       ^~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2786:24: error: incompatible pointer types returning 'const BIO_METHOD *(void)' (aka 'const struct bio_method_st *(void)') from a function with result type 'BIO_METHOD *(*)(void)' (aka 'struct bio_method_st *(*)(void)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return BIO_s_mem;
cargo:warning=                       ^~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2871:24: error: incompatible pointer types returning 'PKCS12 *(const char *, const char *, EVP_PKEY *, X509 *, struct stack_st_X509 *, int, int, int, int, int)' (aka 'PKCS12 *(const char *, const char *, struct evp_pkey_st *, struct x509_st *, struct stack_st_X509 *, int, int, int, int, int)') from a function with result type 'PKCS12 *(*)(char *, char *, EVP_PKEY *, X509 *, struct stack_st_X509 *, int, int, int, int, int)' (aka 'PKCS12 *(*)(char *, char *, struct evp_pkey_st *, struct x509_st *, struct stack_st_X509 *, int, int, int, int, int)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return PKCS12_create;
cargo:warning=                       ^~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2936:24: error: incompatible pointer types returning 'const char *(const SSL_CIPHER *)' (aka 'const char *(const struct ssl_cipher_st *)') from a function with result type 'char *(*)(const SSL_CIPHER *)' (aka 'char *(*)(const struct ssl_cipher_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return SSL_CIPHER_get_version;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2951:24: error: incompatible pointer types returning 'void (SSL_CTX *, SSL_SESSION *(*)(struct ssl_st *, const unsigned char *, int, int *))' (aka 'void (struct ssl_ctx_st *, struct ssl_session_st *(*)(struct ssl_st *, const unsigned char *, int, int *))') from a function with result type 'void (*)(SSL_CTX *, SSL_SESSION *(*)(SSL *, unsigned char *, int, int *))' (aka 'void (*)(struct ssl_ctx_st *, struct ssl_session_st *(*)(struct ssl_st *, unsigned char *, int, int *))') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return SSL_CTX_sess_set_get_cb;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2976:24: error: incompatible pointer types returning 'X509_NAME *(const X509 *)' (aka 'struct X509_name_st *(const struct x509_st *)') from a function with result type 'X509_NAME *(*)(X509 *)' (aka 'struct X509_name_st *(*)(struct x509_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509_get_subject_name;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2981:24: error: incompatible pointer types returning 'X509_NAME *(const X509 *)' (aka 'struct X509_name_st *(const struct x509_st *)') from a function with result type 'X509_NAME *(*)(X509 *)' (aka 'struct X509_name_st *(*)(struct x509_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509_get_issuer_name;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:2996:24: error: incompatible pointer types returning 'void *(const X509 *, int, int *, int *)' (aka 'void *(const struct x509_st *, int, int *, int *)') from a function with result type 'void *(*)(X509 *, int, int *, int *)' (aka 'void *(*)(struct x509_st *, int, int *, int *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509_get_ext_d2i;
cargo:warning=                       ^~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3001:24: error: incompatible pointer types returning 'int (X509_NAME *, int, int, const unsigned char *, int, int, int)' (aka 'int (struct X509_name_st *, int, int, const unsigned char *, int, int, int)') from a function with result type 'int (*)(X509_NAME *, int, int, unsigned char *, int, int, int)' (aka 'int (*)(struct X509_name_st *, int, int, unsigned char *, int, int, int)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509_NAME_add_entry_by_NID;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3006:24: error: incompatible pointer types returning 'int (const X509_NAME *)' (aka 'int (const struct X509_name_st *)') from a function with result type 'int (*)(X509_NAME *)' (aka 'int (*)(struct X509_name_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509_NAME_entry_count;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3011:24: error: incompatible pointer types returning 'X509_NAME_ENTRY *(const X509_NAME *, int)' (aka 'struct X509_name_entry_st *(const struct X509_name_st *, int)') from a function with result type 'X509_NAME_ENTRY *(*)(X509_NAME *, int)' (aka 'struct X509_name_entry_st *(*)(struct X509_name_st *, int)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509_NAME_get_entry;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3016:24: error: incompatible pointer types returning 'ASN1_STRING *(const X509_NAME_ENTRY *)' (aka 'struct asn1_string_st *(const struct X509_name_entry_st *)') from a function with result type 'ASN1_STRING *(*)(X509_NAME_ENTRY *)' (aka 'struct asn1_string_st *(*)(struct X509_name_entry_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509_NAME_ENTRY_get_data;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3021:24: error: incompatible pointer types returning 'ASN1_OBJECT *(const X509_NAME_ENTRY *)' (aka 'struct asn1_object_st *(const struct X509_name_entry_st *)') from a function with result type 'ASN1_OBJECT *(*)(X509_NAME_ENTRY *)' (aka 'struct asn1_object_st *(*)(struct X509_name_entry_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509_NAME_ENTRY_get_object;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3031:24: error: incompatible pointer types returning 'X509_EXTENSION *(CONF *, X509V3_CTX *, int, const char *)' (aka 'struct X509_extension_st *(struct conf_st *, struct v3_ext_ctx *, int, const char *)') from a function with result type 'X509_EXTENSION *(*)(CONF *, X509V3_CTX *, int, char *)' (aka 'struct X509_extension_st *(*)(struct conf_st *, struct v3_ext_ctx *, int, char *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509V3_EXT_nconf_nid;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3036:24: error: incompatible pointer types returning 'X509_EXTENSION *(CONF *, X509V3_CTX *, const char *, const char *)' (aka 'struct X509_extension_st *(struct conf_st *, struct v3_ext_ctx *, const char *, const char *)') from a function with result type 'X509_EXTENSION *(*)(CONF *, X509V3_CTX *, char *, char *)' (aka 'struct X509_extension_st *(*)(struct conf_st *, struct v3_ext_ctx *, char *, char *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return X509V3_EXT_nconf;
cargo:warning=                       ^~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3041:24: error: incompatible pointer types returning 'int (unsigned char **, const ASN1_STRING *)' (aka 'int (unsigned char **, const struct asn1_string_st *)') from a function with result type 'int (*)(unsigned char **, ASN1_STRING *)' (aka 'int (*)(unsigned char **, struct asn1_string_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return ASN1_STRING_to_UTF8;
cargo:warning=                       ^~~~~~~~~~~~~~~~~~~
cargo:warning=/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c:3066:24: error: incompatible pointer types returning 'int (const EVP_PKEY *)' (aka 'int (const struct evp_pkey_st *)') from a function with result type 'int (*)(EVP_PKEY *)' (aka 'int (*)(struct evp_pkey_st *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return EVP_PKEY_bits;
cargo:warning=                       ^~~~~~~~~~~~~
cargo:warning=fatal error: too many errors emitted, stopping now [-ferror-limit=]
cargo:warning=20 errors generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-o" "/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.o" "-c" "/rust/rust-openssl/target/debug/build/systest-8a0914cb68876f1c/out/all.c" with args "cc" did not execute successfully (status code exit code: 1).

', /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.23/src/lib.rs:2253:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by sfackler**
Closes #988

### CODE REVIEW

**Comment by reyk** [comment]
Thanks, I just tested it and it works fine on OpenBSD 6.4-beta with LibreSSL 2.8.0.

**Comment by sfackler** [comment]
Great, I will cut a release tonight.
